services:
  whatsapp-echo-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    # Flask
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=False
    # Logging
      - FLASK_LOG_PATH=/var/log/whatsapp-echo-bot
      - FLASK_LOG_LEVEL=WARNING
    # WhatsApp Cloud API
      - FLASK_WEBHOOK_VERIFICATION_TOKEN=${FLASK_WEBHOOK_VERIFICATION_TOKEN}
      - FLASK_M4D_APP_SECRET=${FLASK_WEBHOOK_VERIFICATION_TOKEN}
      - FLASK_WA_PHONE_NUMBER_ID=${FLASK_WEBHOOK_VERIFICATION_TOKEN}
      - FLASK_WA_BASE_URL=${FLASK_WEBHOOK_VERIFICATION_TOKEN}
      - FLASK_WA_CLOUD_API_ACCESS_TOKEN=${FLASK_WEBHOOK_VERIFICATION_TOKEN}
      - FLASK_WA_CLOUD_API_VERSION=${FLASK_WEBHOOK_VERIFICATION_TOKEN}
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /var/log/whatsapp-echo-bot:/var/log/whatsapp-echo-bot

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - whatsapp-echo-bot
